version: "3"
services:
  php:
    build: .
    volumes:
      - .:/app
    command: tail -F /dev/null
    container_name: stacka_app

  mariadb:
    image: mariadb:10.5.5
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-ChangeMe}
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    container_name: stacka_db
    ports:
      - 3306:3306

volumes:
  db-data:
