version: "3"
services:
  php:
    build: .
    volumes:
      - .:/app
    command: tail -F /dev/null
    container_name: stacka_app

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-ChangeMe}
    container_name: stacka_db
    ports:
      - '3306'

volumes:
  db-data:
